spring:
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non-contextual-creation: true
  datasource:
    url: jdbc:postgresql://localhost/restaurant_advisor
    username: postgres
    password: 1234
  data:
    rest:
      base-path: /api

logging:
  level:
    root: WARN
    com.example.restaurant_advisor_react: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

application-description: Service designed to assist people in choosing a restaurant
application-version: 1.0.0