version: '3.8'
services:

  db:
    build:
      context: services/db
      dockerfile: Dockerfile.db
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: restaurant_advisor
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always

  backend:
    build:
      context: services/back-end
      dockerfile: Dockerfile.backend
    image: restaurant-advisor-react-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/restaurant_advisor
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db

  frontend:
    build:
      context: ../src/main/frontend
      dockerfile: Dockerfile.frontend
    image: restaurant-advisor-react-frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend